modLoader="javafml"
loaderVersion="[34,)"
authors="Luck"
license="GPLv3"

[[mods]]
modId="spark"
displayName="spark"
version="${pluginVersion}"
description="${pluginDescription}"

[[dependencies.spark]]
    modId="forge"
    mandatory=true
    versionRange="[34,)"
    ordering="NONE"
    side="BOTH"
